TwitchAPI:
  ClientID: ""
  CLientSecret: ""

TwitchChannel:
  ChatAccountToken: "" #OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  ReplyChannel: "" #The name of the channel the bot sould work in.

Settings:
  ReplyDelay: 60 #Seconds
  TriggerWord: "Delvin"
  StreamUpTranslation: "Stream läuft wieder"
  StreamDownTranslation: "Stream Offline"

SillySentences: #{USER} {STREAMER} {TIME}
  - "{USER} sag mal... Heißt Tomatenmark Tomatenmark weil Tom Tomaten mag?"
  - "{USER} Werden Krebse eigendlich von Krebserregenden Stoffen erregt?"
  - "Das Meer ist ganz klar eine Suppe!"
  - "{USER} Wenn man sein Ohr ganz leicht auf die Herdplatte drückt, kann man riechen wie dumm man ist?"
  - "Mich braucht jeder! Zumindest behaupten alle ich hätte gerade noch gefehlt‍"
  - "{USER} So So... Ein Thermomix ist also eine Küchenmaschine? Hätte ja auch der heizungsinstallateur bei Asterix und obelix sein können! SeemsGood"
  - "Manche Menschen sind wie schnitzel! Nicht zäh sondern beidseitig bekloppt!"
  - "Ich bin soooo satt. Ich mag keinen.... Oh Kuchen!"
  - "Was Schaust mich so schräg an?"
  - "{STREAMER} der böse {USER} war gemein zu mir ;C"
  - "{USER} Willst du das ich gehe oder wie?"
  - "Ich möchte Hünchen mit REIS!"
  - "{USER} was habe ich den nun schon wieder gemacht?"
  - "{USER} es ist bereits {TIME}. Du musst doch langsam ins bett!"
  - "Warum liegt hier eigentlich Stroh? Und warum hat {USER} gepupst?"
  - "{USER} hat gepupst! NotLikeThis"

StreamUpSentences: #{USER} {STREAMER} {TIME} {UP}
  - "Klingelt {STREAMER}`s Handy etwa schon wieder? - {DOWN}"
  - "Der Stream hat sich verabschiedet. Er ist bestimmt gleich zurück! {STREAMER} - {DOWN}"
  - "{STREAMER} ist bestimmt grade in den Urlaub gefahren! - {DOWN}"
  - "{STREAMER} hat eine Pause eingelegt! Er braucht scheinbar etwas Zeit für sich! - {DOWN}"
  - "{STREAMER} ist wohl in einen Tunnel gefahren! Das Signal mag tunnel scheinbar nicht. - {DOWN}"
  - "{STREAMER} hat sich verlaufen! Er sucht grade den Weg zurück. - {DOWN}"
  - "{STREAMER} scheinbar eingeschlafen. Er träumt grade von uns! - {DOWN}"
  - "{STREAMER} hat Hunger! Bevor er uns isst, geht er etwas zu essen hollen. - {DOWN}"
  - "{STREAMER} ist auf eine Mission gegangen. Er muss die Welt retten! - {DOWN}"
  - "{STREAMER} ist unsichtbar geworden! Er spielt Verstecken mit uns. - {DOWN}"

StreamDownSentences: #{USER} {STREAMER} {TIME} {DOWN}
  - "{STREAMER} ist schon wieder live? PogChamp - {UP}"
  - "{STREAMER} ist zurück aus dem Urlaub. Er hat uns aber nichts mitgebracht! - {UP}"
  - "{STREAMER} hat seine Pause beendet. Er ist bereit, weiterzumachen! - {UP}"
  - "Das Signal hat sich mit dem Tunnel vertagen! {STREAMER} darf jetzt endlich weiter Streamen! - {UP}"
  - "{STREAMER} hat den Weg zurückgefunden! Er war sooo lange weg. ;C - {UP}"
  - "{STREAMER} ist aufgewacht. Er hat wirklich von uns geträumt! - {UP}"
  - "{STREAMER} ist jetzt satt. Er hat etwas Leckeres gegessen! - {UP}"
  - "{STREAMER} hat seine Mission erfüllt. Er hat die Welt gerettet! (Bestimmt...) - {UP}"
  - "{STREAMER} ist sichtbar geworden. Er hat das Versteckspiel gewonnen! - {UP}"
  - "{STREAMER} ist wieder da. Er hat uns wirklich vermisst! - {UP}"