TwitchAPI:
  ClientID: ""
  CLientSecret: ""

TwitchChannel:
  ChatAccountToken: "" #OAuth Token for IRC USer (You can get yours here: http://twitchapps.com/tmi/)
  ReplyChannel: "" #The name of the channel the bot sould work in.

Settings:
  ReplyDelay: 60 #Seconds
  StreamUpTranslation: "Stream läuft wieder"
  StreamDownTranslation: "Stream Offline"
  TriggerWords:
    - "Devlin"
  TimeCommandTriggers:
    - "time"
    - "uhrzeit"
    - "wie spät"

SillySentences: #{USER} {STREAMER} {TIME}
  - "{USER} hat gepupst! NotLikeThis"

StreamUpSentences: #{USER} {STREAMER} {TIME} {UP}
  - "{STREAMER} ist unsichtbar geworden! Er spielt Verstecken mit uns. - {DOWN}"

StreamDownSentences: #{USER} {STREAMER} {TIME} {DOWN}
  - "{STREAMER} ist wieder da. Er hat uns wirklich vermisst! - {UP}"

TimeSentences: #{USER} {STREAMER} {TIME}
  - "Ist es schon {TIME}? Ich sollte mich beeilen und meine Sammlung von Socken sortieren."